/* Rus tilidagi tarjimalar. Kalit — o'zbekcha (lotin) matn. Yangi matn qo'shilsa: node scripts/i18n-keys.mjs --miss */
export const RU: Record<string, string> = {
  " (+60 XP)": " (+60 XP)",
  "+1 oy (naqd)": "+1 мес. (наличными)",
  "1 daqiqa": "1 минута",
  "1 oy": "1 мес.",
  "10 savol · +8 XP": "10 вопр. · +8 XP",
  "10 savol · XP siz": "10 вопр. · без XP",
  "10 ta savol · har biriga 1 daqiqa · teng ballda tezroq yutadi": "10 вопросов · по 1 минуте на каждый · при равных баллах побеждает тот, кто быстрее",
  "10 ta to'g'ri javob ketma-ket": "10 правильных ответов подряд",
  "12 bosqich sertifikati": "Сертификат 12 этапов",
  "12 bosqichning barchasi yakunlandi": "Все 12 этапов пройдены",
  "12 provodka + 8 savol": "12 проводок + 8 вопросов",
  "17:00 da yopildi": "Закрыто в 17:00",
  "17:00 gacha {h} soat {m} daqiqa": "До 17:00: {h} ч {m} мин",
  "2 marta kuchli uchlikka kiring — finalga yo'llanma olasiz": "Войдите в тройку лучших 2 раза — получите путёвку в финал",
  "20 daq": "20 мин",
  "20 provodka · rekord {n}": "20 проводок · рекорд {n}",
  "3 oy": "3 мес.",
  "30 daq": "30 мин",
  "30 kun": "30 дн.",
  "45 daq": "45 мин",
  "5 ta jon": "5 жизней",
  "5 ta to'g'ri javob ketma-ket": "5 правильных ответов подряд",
  "6 oy": "6 мес.",
  "90 kun": "90 дн.",
  "A'zolar": "Участники",
  "Admin kirish": "Вход для админа",
  "Admin panel": "Админ-панель",
  "Admin rejimidan chiqish": "Выйти из режима админа",
  "Aktiv": "Актив",
  "Aktiv va passivni joylang": "Распределите актив и пассив",
  "Andijon viloyati": "Андижанская область",
  "Aniqlik": "Точность",
  "Asosiy": "Главная",
  "Asosiy vositalar": "Основные средства",
  "Avto": "Авто",
  "Avval 5 ta to'g'ri javob bering": "Сначала дайте 5 правильных ответов",
  "Avval ro'yxatdan o'ting": "Сначала зарегистрируйтесь",
  "BAJARILDI": "ВЫПОЛНЕНО",
  "Ba'zi hisobvaraqlar noto'g'ri bo'limda": "Некоторые счета не в том разделе",
  "Bajarilgan · yopildi": "Выполнено · закрыто",
  "Balans o'yini": "Игра «Баланс»",
  "Balans ustasi": "Мастер баланса",
  "Balans yig'ildi! Aktiv = Majburiyatlar + Kapital": "Баланс сошёлся! Актив = Обязательства + Капитал",
  "Balansni xatosiz yig'ish": "Собрать баланс без ошибок",
  "Barcha 12 bosqich": "Все 12 этапов",
  "Barcha natijalar shu telefondan o'chiriladi. Davom etasizmi?": "Все результаты будут удалены с этого телефона. Продолжить?",
  "Bir marta": "Один раз",
  "Birinchi bosqich": "Первый этап",
  "Birinchi chempion juma soat 12:00 da aniqlanadi.": "Первый чемпион определится в пятницу в 12:00.",
  "Birinchi jadval juma soat 12:00 da ochiladi.": "Первая таблица откроется в пятницу в 12:00.",
  "Birlik (so'm)": "Единица (сум)",
  "Bitta bosqichni yakunlash": "Пройти один этап",
  "Blits": "Блиц",
  "Blits bali alohida — haftalik jamiga qo'shilmaydi.": "Баллы блица отдельно — в недельный итог не входят.",
  "Blits yakunlandi": "Блиц завершён",
  "Bo'sh": "Пусто",
  "Bosh buxgalter": "Главный бухгалтер",
  "Bosh hisobchi o'rinbosari": "Зам. главного бухгалтера",
  "Boshlanish": "Начало",
  "Boshlash": "Начать",
  "Boshqa rasm tanlash": "Выбрать другое фото",
  "Boshqa viloyatlar": "Другие области",
  "Bosqich hozir yopiq": "Этап сейчас закрыт",
  "Bosqich yakunlandi!": "Этап пройден!",
  "Bosqich yopilgan — faqat o'z kunida 09:00–17:00 ochiq": "Этап закрыт — открыт только в свой день 09:00–17:00",
  "Bosqichlar": "Этапы",
  "Bosqichlar ish kunlari ochiladi": "Этапы открываются в рабочие дни",
  "Bosqichni 3 yulduz bilan o'tish": "Пройти этап на 3 звезды",
  "Bosqichni boshlash": "Начать этап",
  "Bronza": "Бронза",
  "Bu bosqich bugun yakunlangan": "Этот этап сегодня уже пройден",
  "Bu duelni boshqa odam qabul qilgan": "Эту дуэль уже принял другой человек",
  "Bu raqam boshqa telefonda ro'yxatdan o'tgan. Jamoa administratori «Qurilmani almashtirish» tugmasini bossin — keyin qayta ulaning": "Этот номер зарегистрирован на другом телефоне. Пусть администратор команды нажмёт «Сменить устройство» — затем подключитесь заново",
  "Bu safar raqib kuchliroq": "В этот раз соперник оказался сильнее",
  "Bu yo'nalishda savol yo'q": "В этом разделе нет вопросов",
  "Bugun 09:00 da ochiladi · {h} soat {m} daqiqa qoldi": "Откроется сегодня в 09:00 · осталось {h} ч {m} мин",
  "Bugungi dars": "Урок дня",
  "Bugungi sovg'a olingan — ertaga yana": "Подарок на сегодня получен — завтра снова",
  "Bunday jamoa kodi topilmadi yoki to'xtatilgan": "Код команды не найден или приостановлен",
  "Bunday jamoa topilmadi": "Такая команда не найдена",
  "Bunday sertifikat topilmadi": "Такой сертификат не найден",
  "Butun ekran": "Полный экран",
  "Buxgalter lavozimiga test": "Тест на должность бухгалтера",
  "Buxgalterlar ligasi": "Лига бухгалтеров",
  "Buxgalterlar uchun haftalik liga": "Еженедельная лига для бухгалтеров",
  "Buxoro viloyati": "Бухарская область",
  "Ch": "Ср",
  "Chek": "Чек",
  "Chek rad etilsinmi? Ishtirokchining obunasi bekor qilinadi.": "Отклонить чек? Подписка участника будет отменена.",
  "Chek rasmini qayta tanlang (JPG yoki PNG)": "Выберите фото чека заново (JPG или PNG)",
  "Chek rasmini tanlash": "Выбрать фото чека",
  "Chekingiz administratorga yuborildi. Bosqichlar ochildi — har ish kuni 09:00–17:00.": "Ваш чек отправлен администратору. Этапы открыты — каждый рабочий день 09:00–17:00.",
  "Cheklar": "Чеки",
  "Cheklarni Telegramda olish": "Получать чеки в Telegram",
  "Chekni administrator tekshiradi. Chek soxta yoki summa kam bo'lsa, obuna bekor qilinadi.": "Чек проверит администратор. Если чек поддельный или сумма меньше нужной, подписка будет отменена.",
  "Chekni botga yuborish": "Отправить чек боту",
  "Chekni yuborish": "Отправить чек",
  "Chempionlar zali": "Зал чемпионов",
  "Chiqasizmi? Bu mashq natijasi saqlanmaydi.": "Выйти? Результат этой тренировки не сохранится.",
  "Chiqasizmi? Javobsiz savol XATO hisoblanadi va qaytib chiqmaydi. Topgan XP saqlanadi.": "Выйти? Вопрос без ответа засчитается как ОШИБКА и больше не появится. Заработанные XP сохранятся.",
  "Chiqish": "Выйти",
  "Chiqsangiz, natijangiz shu holatda yuboriladi va qayta kirib bo'lmaydi.": "Если выйдете, результат будет отправлен в текущем виде, и войти снова будет нельзя.",
  "Chorshanba": "Среда",
  "Dam olish kuni": "Выходной",
  "Dam olish kuni — XP berilmaydi.": "Выходной — XP не начисляются.",
  "Daraja": "Уровень",
  "Darajalar har juma 12:10 da yangilanadi.": "Уровни обновляются каждую пятницу в 12:10.",
  "Davom etish": "Продолжить",
  "Debet": "Дебет",
  "Debet (masalan 5010)": "Дебет (например, 5010)",
  "Do'stingiz havolangiz orqali qo'shilib, birinchi to'lovni qilsa, sizga obunaga 7 kun qo'shiladi.": "Если друг присоединится по вашей ссылке и сделает первую оплату, вам добавится 7 дней подписки.",
  "Du": "Пн",
  "Duel": "Дуэль",
  "Duel holati": "Статус дуэли",
  "Duel muddati tugagan": "Срок дуэли истёк",
  "Duel natijangiz": "Ваш результат в дуэли",
  "Duel topilmadi": "Дуэль не найдена",
  "Duel yakunlangan": "Дуэль завершена",
  "Duel yaratish va yuborish": "Создать и отправить дуэль",
  "Duelchi": "Дуэлянт",
  "Duelda g'alaba": "Победа в дуэли",
  "Duellar": "Дуэли",
  "Durang!": "Ничья!",
  "Dushanba": "Понедельник",
  "Eng yuqori daraja!": "Высший уровень!",
  "Familiya": "Фамилия",
  "Familiyani kiriting": "Введите фамилию",
  "Faqat liga administratori uchun. PIN kodni kiriting.": "Только для администратора лиги. Введите PIN-код.",
  "Farg'ona viloyati": "Ферганская область",
  "Final": "Финал",
  "Final hozir yopiq": "Финал сейчас закрыт",
  "Final natijalari": "Итоги финала",
  "Final yakunlandi!": "Финал завершён!",
  "Final yopiq — faqat oyning oxirgi shanbasi 10:00–13:00": "Финал закрыт — только в последнюю субботу месяца 10:00–13:00",
  "Final: {d}, shanba 10:00–13:00 · 20 savol · teng ballda tezroq ishlagan yutadi": "Финал: {d}, суббота 10:00–13:00 · 20 вопросов · при равных баллах побеждает тот, кто быстрее",
  "Finalchilar": "Финалисты",
  "Finalchilar hali boshlamadi": "Финалисты ещё не начали",
  "Finalga kirish": "Вход в финал",
  "Finalni boshlash": "Начать финал",
  "Hafta": "Неделя",
  "Hafta davomida faqat o'z natijangizni ko'rasiz.": "В течение недели вы видите только свой результат.",
  "Hafta davomida natijangizni faqat siz ko'rasiz. Jadval juma 12:00 da ochiladi.": "В течение недели ваш результат видите только вы. Таблица откроется в пятницу в 12:00.",
  "Haftada 400 XP dan kam to'plasangiz — bir daraja pastga.": "Наберёте за неделю меньше 400 XP — на уровень ниже.",
  "Haftada jamoangiz kuchli uchligiga kirsangiz yoki 1600 XP to'plasangiz — bir daraja yuqoriga.": "Войдёте за неделю в тройку лучших своей команды или наберёте 1600 XP — на уровень выше.",
  "Haftalik g'olib sertifikati": "Сертификат победителя недели",
  "Haftalik liga": "Недельная лига",
  "Haftalik liga yakunlandi!": "Недельная лига завершена!",
  "Haftalik liga — {n}-o'rin": "Недельная лига — {n}-е место",
  "Haftalik ligada 1-o'rin": "1-е место в недельной лиге",
  "Haftalik sovg'a: +{n} XP": "Подарок недели: +{n} XP",
  "Haftaning savoli": "Вопрос недели",
  "Hali a'zolar yo'q": "Участников пока нет",
  "Hali chek yo'q.": "Чеков пока нет.",
  "Hali duel yo'q": "Дуэлей пока нет",
  "Hali nomzod yo'q": "Кандидатов пока нет",
  "Hali saralanganlar yo'q. Oy davomida 2 marta kuchli uchlikka kiring.": "Отобранных пока нет. Войдите в тройку лучших 2 раза за месяц.",
  "Hali savol yo'q": "Вопросов пока нет",
  "Hali taklif yo'q.": "Приглашений пока нет.",
  "Halol o'yin: savol ochiq turganda ilovadan chiqsangiz (boshqa ilova, brauzer, sun'iy intellekt) — savol avtomatik xato hisoblanadi. Matnni nusxalab bo'lmaydi, ekranda ismingiz yozilgan.": "Честная игра: если выйдете из приложения, пока вопрос открыт (в другое приложение, браузер, ИИ), — вопрос автоматически засчитается как ошибка. Текст нельзя скопировать, на экране написано ваше имя.",
  "Hamkasbingizni bahsga chaqiring": "Вызовите коллегу на спор",
  "Hamkasbingizni chaqiring": "Вызовите коллегу",
  "Hammasi joylandi — tekshiring": "Всё распределено — проверьте",
  "Har ish kuni 20 ta savol. Juma kuni — g'oliblar.": "Каждый рабочий день 20 вопросов. В пятницу — победители.",
  "Har ish kuni bittadan bosqich: faqat o'z kunida 09:00 dan 17:00 gacha ochiq.": "Каждый рабочий день по одному этапу: открыт только в свой день с 09:00 до 17:00.",
  "Har jamoaning eng yaxshi 3 nafari bali qo'shiladi · o'tgan hafta": "Суммируются баллы 3 лучших в каждой команде · прошлая неделя",
  "Har kuni 1 daqiqalik qoida · {n} ta dars": "Каждый день правило на 1 минуту · уроков: {n}",
  "Havola": "Ссылка",
  "Havola nusxalandi": "Ссылка скопирована",
  "Hisob": "Расчёт",
  "Hisobchi": "Бухгалтер",
  "Hisobchi Liga natijam": "Мой результат в Hisobchi Liga",
  "Hisobchi Liga · rahbar uchun oylik hisobot · tuzilgan: {d}": "Hisobchi Liga · ежемесячный отчёт для руководителя · составлен: {d}",
  "Hisobingiz boshqa telefonga o'tkazilgan.": "Ваш аккаунт перенесён на другой телефон.",
  "Hisobingiz bu telefonga ulanmagan — «Qayta ulanish» tugmasini bosing": "Ваш аккаунт не привязан к этому телефону — нажмите «Подключиться заново»",
  "Hisobingiz himoyalandi": "Ваш аккаунт защищён",
  "Hisobingiz tiklandi": "Ваш аккаунт восстановлен",
  "Hisoblang": "Посчитайте",
  "Hisobot": "Отчёт",
  "Hisobvaraqlarni aktiv, majburiyat va kapitalga ajrating": "Распределите счета по активу, обязательствам и капиталу",
  "Hisobvaraqni bosing, keyin bo'limni tanlang. Oxirida Aktiv = Majburiyatlar + Kapital bo'lishi kerak.": "Нажмите на счёт, затем выберите раздел. В итоге должно быть: Актив = Обязательства + Капитал.",
  "Hisobvaraqni tanlang": "Выберите счёт",
  "Ikkalangizga bir xil 10 ta savol. Kim ko'proq to'g'ri topsa — g'olib, teng bo'lsa tezrog'i.": "Вам обоим — одни и те же 10 вопросов. Кто ответит правильно на большее число — победитель, при равенстве — кто быстрее.",
  "Ilova havolasi": "Ссылка на приложение",
  "Ilovadan chiqildi — savol xato hisoblandi": "Вы вышли из приложения — вопрос засчитан как ошибка",
  "Ish haqi": "Зарплата",
  "Ishga olayotgan buxgalteringizga havola yuboring: u ro'yxatdan o'tmasdan test ishlaydi, natijasi shu yerda ko'rinadi.": "Отправьте ссылку бухгалтеру, которого нанимаете: он пройдёт тест без регистрации, результат появится здесь.",
  "Ishonchingiz komilmi?": "Вы уверены?",
  "Ishtirokchi chek yuborishi bilan ligaga qo'shiladi. Chek soxta bo'lsa — «Rad etish».": "Участник попадает в лигу, как только отправит чек. Если чек поддельный — «Отклонить».",
  "Ism": "Имя",
  "Ism va familiya": "Имя и фамилия",
  "Ism va familiyani kiriting": "Введите имя и фамилию",
  "Ismni kiriting": "Введите имя",
  "Izoh (nega to'g'ri)": "Пояснение (почему верно)",
  "Jadval har 5 soniyada yangilanadi. Yakuniy natija 13:00 da e'lon qilinadi.": "Таблица обновляется каждые 5 секунд. Итоговый результат объявят в 13:00.",
  "Jadval juma 12:00 da shakllanadi.": "Таблица формируется в пятницу в 12:00.",
  "Jadvalni ko'rish": "Смотреть таблицу",
  "Jamoa": "Команда",
  "Jamoa a'zolari": "Участники команды",
  "Jamoa kodi": "Код команды",
  "Jamoa kodini tekshiring yoki bo'sh qoldiring": "Проверьте код команды или оставьте поле пустым",
  "Jamoa nomi": "Название команды",
  "Jamoa obunasi tugagan — administratorga murojaat qiling": "Подписка команды истекла — обратитесь к администратору",
  "Jamoa savollari": "Вопросы команды",
  "Jamoa to'xtatilgan": "Команда приостановлена",
  "Jamoa yaratish": "Создать команду",
  "Jamoada {n}-o'rin": "{n}-е место в команде",
  "Jamoalar": "Команды",
  "Jamoangiz uchun «Haftaning savoli»ni tuzing — savol ismingiz bilan chiqadi.": "Составьте «Вопрос недели» для своей команды — он выйдет с вашим именем.",
  "Javob": "Ответ",
  "Javob berish": "Ответить",
  "Jizzax viloyati": "Джизакская область",
  "Jonlar": "Жизни",
  "Jonlar tugadi": "Жизни закончились",
  "Jonli jadval": "Живая таблица",
  "Ju": "Пт",
  "Juda ko'p urinish — birozdan keyin qayta urinib ko'ring": "Слишком много попыток — попробуйте чуть позже",
  "Juma": "Пятница",
  "Kamida 2 ta variant kiriting": "Введите минимум 2 варианта",
  "Kapital": "Капитал",
  "Karta": "Карта",
  "Karta egasi": "Владелец карты",
  "Karta raqami": "Номер карты",
  "Karta raqami 16 xonali bo'lishi kerak": "Номер карты должен содержать 16 цифр",
  "Karta raqami tez orada qo'shiladi. Hozircha yozing: @murtozo_44": "Номер карты скоро добавим. Пока пишите: @murtozo_44",
  "Kartaga o'tkazing": "Переведите на карту",
  "Keyingi bosqich: {d}, 09:00": "Следующий этап: {d}, 09:00",
  "Kichik hisobchi": "Младший бухгалтер",
  "Kirish": "Войти",
  "Ko'rinish": "Внешний вид",
  "Kod": "Код",
  "Kredit": "Кредит",
  "Kredit (masalan 5110)": "Кредит (например, 5110)",
  "Kuchli uchlikka kiring yoki 12 bosqichni yakunlang — QR kodli sertifikat olasiz.": "Войдите в тройку лучших или пройдите 12 этапов — получите сертификат с QR-кодом.",
  "Kumush": "Серебро",
  "Kunlik mashq": "Ежедневная тренировка",
  "Kunlik seriya bonusi: +{n} XP": "Бонус за ежедневную серию: +{n} XP",
  "Kunlik sovg'a": "Ежедневный подарок",
  "Kutilmoqda": "Ожидается",
  "Liga bir bosishda ochiladi": "Лига открывается в одно касание",
  "Liga darajalari": "Уровни лиги",
  "Liga g'olibi": "Победитель лиги",
  "Ligada qatnashish: oyiga {p} so'm. Ro'yxatdan o'tgach kartaga to'lab, chekni yuborasiz — shu zahoti ligaga qo'shilasiz.": "Участие в лиге: {p} сум в месяц. После регистрации оплатите на карту и отправьте чек — сразу попадёте в лигу.",
  "Ligada qatnashish: oyiga {p} so'm. To'lovdan keyin bosqichlar ochiladi.": "Участие в лиге: {p} сум в месяц. После оплаты этапы откроются.",
  "Ligaga qo'shildingiz": "Вы в лиге",
  "Ligaga qo'shildingiz!": "Вы в лиге!",
  "Ligaga qo'shiling": "Присоединяйтесь к лиге",
  "Ligaga qo'shilish": "Вступить в лигу",
  "Ligaga qo'shilish uchun obuna kerak": "Для участия в лиге нужна подписка",
  "Ma'lumot yuklanmoqda...": "Загрузка данных...",
  "Ma'lumotlarni tekshiring": "Проверьте данные",
  "Majburiyatlar": "Обязательства",
  "Majburiyatlar + Kapital": "Обязательства + Капитал",
  "Mashq bajarildi!": "Тренировка выполнена!",
  "Mashq va darslar": "Тренировки и уроки",
  "Mashqchi": "Практик",
  "Mavzu bo'yicha 10 ta savol. Ball kunlik mashq hisobiga yoziladi — liga jamiga qo'shilmaydi.": "10 вопросов по теме. Баллы идут в ежедневную тренировку — в общий счёт лиги не входят.",
  "Men ham o'ynayman": "Я тоже играю",
  "Mening duellarim": "Мои дуэли",
  "Mening sertifikatlarim": "Мои сертификаты",
  "Menyu": "Меню",
  "Mini-darslar": "Мини-уроки",
  "Moliya direktori": "Финансовый директор",
  "Muallif: {n} — o'tgan hafta g'olibi": "Автор: {n} — победитель прошлой недели",
  "Muddatsiz": "Бессрочно",
  "Namangan viloyati": "Наманганская область",
  "Natija kartochkasi": "Карточка результата",
  "Natija yuborildi. Raqibingiz o'ynagach g'olib ko'rinadi.": "Результат отправлен. Победитель станет известен, когда сыграет соперник.",
  "Natijalar": "Результаты",
  "Natijangiz kompaniyaga yuborildi. Rahmat!": "Ваш результат отправлен в компанию. Спасибо!",
  "Natijangiz yuborildi. G'olib 13:00 da aniqlanadi.": "Ваш результат отправлен. Победитель определится в 13:00.",
  "Natijani ko'rish": "Смотреть результат",
  "Natijani ulashish": "Поделиться результатом",
  "Navoiy viloyati": "Навоийская область",
  "Nomini kiriting": "Введите название",
  "Nusxa olindi": "Скопировано",
  "Nusxa olish": "Копировать",
  "O'chirilgan": "Выключено",
  "O'qildi": "Прочитано",
  "O'qish": "Читать",
  "O'tgan hafta natijalari": "Итоги прошлой недели",
  "O'tgan hafta {n}-o'rin": "{n}-е место на прошлой неделе",
  "Obuna": "Подписка",
  "Obuna {d} gacha": "Подписка до {d}",
  "Obunangiz {d} gacha faol. Quyida uzaytirishingiz mumkin.": "Ваша подписка активна до {d}. Ниже можно её продлить.",
  "Ochiq — bugun 17:00 gacha": "Открыто — сегодня до 17:00",
  "Ochish": "Открыть",
  "Olish mumkin": "Можно забрать",
  "Olmos": "Алмаз",
  "Oltin": "Золото",
  "Orqaga": "Назад",
  "Ovoz va tebranish": "Звук и вибрация",
  "Oxirgi faollik": "Последняя активность",
  "Oy chempioniga maxsus sovg'a tayyorlangan — final kuni ochiladi.": "Для чемпиона месяца приготовлен особый подарок — откроется в день финала.",
  "Oy jami": "Итого за месяц",
  "Oyiga {p} so'm · to'lab, chekni yuboring": "{p} сум в месяц · оплатите и отправьте чек",
  "Oylik chempionat": "Ежемесячный чемпионат",
  "Oylik final": "Финал месяца",
  "Oylik final boshlandi!": "Финал месяца начался!",
  "Oylik hisobot": "Ежемесячный отчёт",
  "PDF saqlash / chop etish": "Сохранить PDF / печать",
  "PIN eskirgan — qayta kiring": "PIN устарел — войдите заново",
  "PIN kiriting": "Введите PIN",
  "PIN kod": "PIN-код",
  "PIN noto'g'ri": "Неверный PIN",
  "Pa": "Чт",
  "Payme / Click orqali to'lash": "Оплатить через Payme / Click",
  "Payshanba": "Четверг",
  "Profil": "Профиль",
  "Provodka": "Проводка",
  "Provodka tuzing": "Составьте проводку",
  "Provodka ustozi": "Мастер проводок",
  "Provodka, QQS, ish haqi, asosiy vositalar, soliqlar, hisobotlar va qonunchilik": "Проводки, НДС, зарплата, основные средства, налоги, отчётность и законодательство",
  "QQS, ish haqi, MHXS va boshqalar · bazada {n} ta savol": "НДС, зарплата, МСФО и другое · в базе вопросов: {n}",
  "QR kod bilan tekshiriladi": "Проверяется по QR-коду",
  "QR kodni skanerlab haqiqiyligini tekshiring": "Отсканируйте QR-код, чтобы проверить подлинность",
  "Qabul qilish va boshlash": "Принять и начать",
  "Qanday ko'tariladi": "Как повысить уровень",
  "Qashqadaryo viloyati": "Кашкадарьинская область",
  "Qayta ulanish": "Переподключиться",
  "Qaytish": "Вернуться",
  "Qizil bilan belgilangan hisobvaraqlar boshqa bo'limga tegishli. 0–5 guruh — aktiv, 6–7 — majburiyat, 8 — kapital.": "Счета, отмеченные красным, относятся к другому разделу. Группы 0–5 — активы, 6–7 — обязательства, 8 — капитал.",
  "Qo'shilgan savollar": "Добавленные вопросы",
  "Qo'shimcha mashq": "Дополнительная тренировка",
  "Qo'shimcha o'qitish tavsiya etiladi": "Рекомендуется дополнительное обучение",
  "Qolish": "Остаться",
  "Qoraqalpog'iston Respublikasi": "Республика Каракалпакстан",
  "Qurilma": "Устройство",
  "Qutida kichik sovg'a": "В коробке маленький подарок",
  "Rad etildi": "Отклонено",
  "Rad etish": "Отклонить",
  "Raqib kutilmoqda": "Ожидание соперника",
  "Raqib o'ynashini kutyapmiz": "Ждём, пока сыграет соперник",
  "Reyting": "Рейтинг",
  "Reytingda 1-o'rin": "1-е место в рейтинге",
  "Ro'yxatdan o'tish": "Регистрация",
  "Samarqand viloyati": "Самаркандская область",
  "Saqlandi": "Сохранено",
  "Saqlash": "Сохранить",
  "Savol": "Вопрос",
  "Savol kamida 10 belgi": "Вопрос — минимум 10 символов",
  "Savol qo'shish": "Добавить вопрос",
  "Savol taklif qilish": "Предложить вопрос",
  "Savol topilmadi": "Вопрос не найден",
  "Savolingiz admin tasdiqlagach, jamoangizga ismingiz bilan chiqadi.": "После одобрения админом ваш вопрос появится в команде с вашим именем.",
  "Savollar": "Вопросы",
  "Savolni tahrirlash": "Редактировать вопрос",
  "Se": "Вт",
  "Sertifikat": "Сертификат",
  "Sertifikat haqiqiy": "Сертификат подлинный",
  "Sertifikat uchun shart bajarilmagan": "Условие для сертификата не выполнено",
  "Sertifikatlar": "Сертификаты",
  "Sertifikatni tekshirish": "Проверить сертификат",
  "Serverga ulanib bo'lmadi — internetni tekshiring": "Не удалось подключиться к серверу — проверьте интернет",
  "Seshanba": "Вторник",
  "Shanba": "Суббота",
  "Shanba va yakshanba sovg'a yo'q": "В субботу и воскресенье подарков нет",
  "Shu telefondagi ma'lumotni tozalash": "Очистить данные на этом телефоне",
  "Sinov muddati yo'q. Jamoa keyingi dushanbadan boshlanadi.": "Пробного периода нет. Команда стартует со следующего понедельника.",
  "Sirdaryo viloyati": "Сырдарьинская область",
  "Siz bu oy finalga saralanmagansiz": "Вы не прошли отбор в финал этого месяца",
  "Siz buni allaqachon bajargansiz": "Вы уже это выполнили",
  "Siz finalni ishladingiz: {s} ball": "Вы прошли финал. Баллы: {s}",
  "Siz o'tgan hafta g'olibisiz!": "Вы победитель прошлой недели!",
  "Siz saralandingiz!": "Вы прошли отбор!",
  "Siz saralangansiz · 13:00 gacha": "Вы прошли отбор · до 13:00",
  "Siz shu yerdasiz": "Вы здесь",
  "Siz taklif qilganlar: {n}": "Приглашено вами: {n}",
  "Siz yutdingiz! 🎉": "Вы победили! 🎉",
  "Sizni Hisobchi Ligada duelga chaqiraman: 10 ta savol, kim tezroq va aniqroq? ⚔️": "Вызываю вас на дуэль в Hisobchi Liga: 10 вопросов — кто быстрее и точнее? ⚔️",
  "Soat 17:00 — bosqich yopildi": "17:00 — этап закрыт",
  "Soliqlar": "Налоги",
  "Sovg'a ochildi!": "Подарок открыт!",
  "Sovg'ani ochish": "Открыть подарок",
  "Sozlamalar": "Настройки",
  "Stajyor": "Стажёр",
  "Superadmin": "Суперадмин",
  "Superadmin rejimidan chiqish": "Выйти из режима суперадмина",
  "Surxondaryo viloyati": "Сурхандарьинская область",
  "TO'G'RI": "ВЕРНО",
  "Taklif faqat o'tgan hafta g'olibi uchun": "Предложение только для победителя прошлой недели",
  "Taklif havolasi (bot)": "Ссылка-приглашение (бот)",
  "Taklif kodi": "Код приглашения",
  "Taklif qiling — +7 kun bepul": "Пригласите — +7 дней бесплатно",
  "Tasdiqlandi": "Подтверждено",
  "Tasdiqlash": "Подтвердить",
  "Tayyor — yangi telefonda ro'yxatdan o'tsin": "Готово — пусть зарегистрируется на новом телефоне",
  "Tekshirilmoqda...": "Проверяем...",
  "Tekshirish": "Проверить",
  "Tekshirish QR kodi": "QR-код для проверки",
  "Telefon ekraniga qo'shish": "Добавить на экран телефона",
  "Telefon raqam": "Номер телефона",
  "Telefon raqam: +998 XX XXX XX XX": "Номер телефона: +998 XX XXX XX XX",
  "Telefon raqamingizni faqat jamoa administratori ko'radi. Natijangizni faqat shu telefon yoza oladi.": "Ваш номер видит только администратор команды. Записывать ваш результат может только этот телефон.",
  "Telegram guruhingizga botni qo'shing va guruhda /ulash {c} deb yozing.": "Добавьте бота в вашу группу Telegram и напишите в группе /ulash {c}.",
  "Test": "Тест",
  "Test bir marta ishlanadi. Savol paytida ilovadan chiqsangiz, savol xato hisoblanadi. Natija kompaniyaga yuboriladi.": "Тест проходится один раз. Если выйти из приложения во время вопроса, ответ засчитается как ошибка. Результат отправляется компании.",
  "Test nomi": "Название теста",
  "Test topilmadi yoki yopilgan.": "Тест не найден или закрыт.",
  "Test yakunlandi": "Тест завершён",
  "Test yaratish": "Создать тест",
  "Test yopilgan": "Тест закрыт",
  "Testlar": "Тесты",
  "Testni boshlash": "Начать тест",
  "Til": "Язык",
  "Til, mavzu, ovoz": "Язык, тема, звук",
  "To'g'ri javob (raqam)": "Правильный ответ (число)",
  "To'g'ri javob varianti bo'sh": "Вариант правильного ответа пуст",
  "To'g'ri!": "Верно!",
  "To'g'ri! +50 XP": "Верно! +50 XP",
  "To'lov kartasi": "Платёжная карта",
  "To'lov kutilmoqda": "Ожидается оплата",
  "To'lov qilish": "Оплатить",
  "To'xtatish": "Остановить",
  "Top-3": "Топ-3",
  "Topgan XP saqlandi. Javob berilgan savollar qaytmaydi — «Davom etish» bilan qolganlarini ishlaysiz.": "Заработанные XP сохранены. Отвеченные вопросы не повторяются — «Продолжить», чтобы решить остальные.",
  "Topilmadi": "Не найдено",
  "Toshkent shahri": "город Ташкент",
  "Toshkent viloyati": "Ташкентская область",
  "Tozalandi": "Очищено",
  "Tungi": "Ночная",
  "Tushundim · +15 XP": "Понятно · +15 XP",
  "Ulashish": "Поделиться",
  "Umumiy savollar": "Общие вопросы",
  "Uzaytirildi": "Продлено",
  "Uzaytirish": "Продлить",
  "Vaqt tugadi": "Время вышло",
  "Viloyat": "Область",
  "Viloyat ligasi": "Лига области",
  "Viloyat ligasi uchun: jamoangizning eng yaxshi 3 nafari viloyatdagi boshqa jamoalar bilan bellashadi.": "Для лиги области: 3 лучших участника вашей команды соревнуются с другими командами области.",
  "Viloyatingiz": "Ваша область",
  "Viloyatni tanlang": "Выберите область",
  "XATO": "ОШИБКА",
  "XP bu hafta": "XP за неделю",
  "Xato daftari": "Тетрадь ошибок",
  "Xato daftari bo'sh — zo'r!": "Тетрадь ошибок пуста — отлично!",
  "Xato — sababini ko'ring": "Ошибка — посмотрите причину",
  "Xato. Ishtirok uchun +10 XP": "Ошибка. За участие +10 XP",
  "Xatosiz": "Без ошибок",
  "Xodim": "Сотрудник",
  "Xodim tanlash testi": "Тест для отбора сотрудников",
  "Xorazm viloyati": "Хорезмская область",
  "Yakshanba": "Воскресенье",
  "Yakunlandi": "Завершено",
  "Yakunlash": "Завершить",
  "Yana": "Ещё",
  "Yangi balans": "Новый баланс",
  "Yangi jamoa": "Новая команда",
  "Yangi liga boshlandi — hisob noldan. Darajalar 12:10 da yangilanadi.": "Новая лига началась — счёт с нуля. Уровни обновятся в 12:10.",
  "Yangi o'yin": "Новая игра",
  "Yangi rekord!": "Новый рекорд!",
  "Yangi savol": "Новый вопрос",
  "Yangi yutuq": "Новое достижение",
  "Yarim yo'l": "Полпути",
  "Yetakchi": "Лидер",
  "Yiqilgan bosqichni qayta o'tish": "Перепройти проваленный этап",
  "Yo'nalish mashqi bajarildi!": "Тренировка по направлению выполнена!",
  "Yo'nalishlar": "Направления",
  "Yopildi · {d}": "Закрыто · {d}",
  "Yopish": "Закрыть",
  "Yoqilgan": "Включено",
  "Yoqish": "Включить",
  "Yorug'": "Светлая",
  "Yuborildi": "Отправлено",
  "Yuborildi — admin tasdiqlaydi": "Отправлено — админ подтвердит",
  "Yuborilmoqda...": "Отправляем...",
  "Yuborish": "Отправить",
  "Yuklanmoqda...": "Загрузка...",
  "Yutuqlar": "Достижения",
  "Zaif mavzu: «{s}». Xato daftarida mashq qiling.": "Слабая тема: «{s}». Потренируйтесь в Тетради ошибок.",
  "Zal": "Зал",
  "Zaxiralar": "Резервы",
  "aniqlik": "точность",
  "ball": "балл",
  "bo'lmasa bo'sh qoldiring": "если нет — оставьте пустым",
  "bosqich": "этап",
  "bosqich XP": "XP за этап",
  "bu hafta": "на этой неделе",
  "bugungi": "сегодняшний",
  "chek tekshirilmoqda": "чек проверяется",
  "davom etasiz": "продолжите",
  "ertaga yana": "завтра снова",
  "faol": "активна",
  "faqat raqam": "только цифры",
  "hafta": "неделя",
  "hafta XP": "XP за неделю",
  "har savolga": "на каждый вопрос",
  "har savolga 1 daqiqa": "1 минута на вопрос",
  "ishlamoqda": "в процессе",
  "ixtiyoriy": "необязательно",
  "jami {xp} XP · {s} bosqich · {d} kun": "всего {xp} XP · этапов: {s} · дней: {d}",
  "jonli": "живая",
  "juma 12:00": "пятница 12:00",
  "kechikdi": "опоздал",
  "kuchli uchlikda: {n} marta": "в топ-3: {n} раз",
  "kun": "день",
  "kunlik seriya": "серия дней",
  "liga": "лига",
  "maqsad": "цель",
  "muddatsiz": "бессрочно",
  "o'chirish": "удалить",
  "o'rtacha aniqlik": "средняя точность",
  "o'zgartirish": "изменить",
  "obuna to'lanmagan": "подписка не оплачена",
  "obuna {d} gacha": "подписка до {d}",
  "ochiq": "открыт",
  "ochishga tayyor": "готов к открытию",
  "provodka, hisob, test": "проводка, учёт, тест",
  "rad etilgan": "отклонён",
  "siz": "вы",
  "so'm": "сум",
  "tahrir": "ред.",
  "tasdiqlangan": "подтверждён",
  "tekshirilmagan": "не проверен",
  "to'g'ri": "верно",
  "to'lanmagan": "не оплачено",
  "to'xtatilgan": "приостановлено",
  "vaqt": "время",
  "variant": "вариант",
  "xato": "ошибка",
  "xatoda kamayadi": "уменьшается при ошибке",
  "xodim": "сотрудник",
  "yakunladi": "завершил",
  "yangi": "новый",
  "yoki chekni shu yerda yuklang": "или загрузите чек здесь",
  "yopiq": "закрыт",
  "yoqish": "включить",
  "{t} liga": "Лига «{t}»",
  "{a}/{b} to'g'ri javob": "{a}/{b} верных ответов",
  "{d} kun {h} soat": "{d} дн. {h} ч",
  "{d}/20 savol": "{d}/20 вопр.",
  "{d}/{n} savol": "{d}/{n} вопр.",
  "{h} soat": "{h} ч",
  "{m} chempionati": "Чемпионат {m}",
  "{m} daqiqa": "{m} мин",
  "{n} ishtirokchi": "Участников: {n}",
  "{n} ishtirokchi · natijalar faqat sizga ko'rinadi": "Участников: {n} · результаты видите только вы",
  "{n} kunlik seriya — davom eting!": "Серия {n} дн. — продолжайте!",
  "{n} ligadan o'chirilsinmi?": "Удалить {n} из лиги?",
  "{n} oy": "{n} мес.",
  "{n} savol": "{n} вопр.",
  "{n} savol · {m} daqiqa · {k} nomzod": "{n} вопр. · {m} мин · кандидатов: {k}",
  "{n} ta guruh ulangan": "Подключено групп: {n}",
  "{n} ta savol": "Вопросов: {n}",
  "{n} uchun 1 oylik to'lov qabul qilindimi?": "Оплата за 1 месяц от {n} получена?",
  "{n} yangi telefonga o'tadimi? Natijalar saqlanadi.": "Перенести {n} на новый телефон? Результаты сохранятся.",
  "{n}-bosqich": "Этап {n}",
  "{n}-bosqich {d} soat 09:00 da ochiladi": "Этап {n} откроется {d} в 09:00",
  "{n}-mavsum — bosqichlar yangidan boshlandi": "Сезон {n} — этапы начались заново",
  "{xp} XP · hafta yakuni {d}": "{xp} XP · итоги недели {d}",
  "«{n}» obunasi tugagan. Bosqichlar yopiq — administratorga murojaat qiling.": "Подписка «{n}» истекла. Этапы закрыты — обратитесь к администратору.",
  "«{r}» uchun yana {n} XP": "Ещё {n} XP до «{r}»",
  "— tanlang —": "— выберите —",
  "— viloyat —": "— область —",
  "⛔ To'lanmagan — bosqichlar yopiq": "⛔ Не оплачено — этапы закрыты",
  "✅ Bajarildi · bugun": "✅ Выполнено · сегодня",
  "✅ Bajarilgan · {xp} XP": "✅ Выполнено · {xp} XP",
  "✅ {d} gacha faol": "✅ Активна до {d}",
  "✅ {ok} to'g'ri · ❌ {bad} xato · {xp} XP": "✅ {ok} верно · ❌ {bad} неверно · {xp} XP",
  "🔥 5 ketma-ket!": "🔥 5 подряд!",
  "Bosqich yopilgan — faqat o'z kunida ochiq: 09:00–17:00, juma 09:00–12:00": "Этап закрыт — открыт только в свой день: 09:00–17:00, в пятницу 09:00–12:00",
  "Chekingiz administratorga yuborildi. Bosqichlar ochildi — har ish kuni 09:00–17:00, juma 09:00–12:00.": "Ваш чек отправлен администратору. Этапы открыты — каждый рабочий день 09:00–17:00, в пятницу 09:00–12:00.",
  "Har bosqichdan keyin balingiz, ertalab bosqich eslatmasi, juma kuni o'rningiz — shaxsan sizga.": "Баллы после каждого этапа, утреннее напоминание и ваше место в пятницу — лично вам.",
  "Har ish kuni bittadan bosqich: faqat o'z kunida 09:00 dan 17:00 gacha ochiq, juma kuni 12:00 gacha.": "Каждый рабочий день по одному этапу: открыт только в свой день с 09:00 до 17:00, в пятницу — до 12:00.",
  "Natijalar va eslatmalar shaxsan sizga": "Результаты и напоминания лично вам",
  "Natijangiz Telegram'ga kelsin": "Получайте результаты в Telegram",
  "Ochiq — bugun {c} gacha": "Открыто — сегодня до {c}",
  "Soat {c} — bosqich yopildi": "{c} — этап закрыт",
  "Telegram'ni ulash": "Подключить Telegram",
  "Ulash": "Подключить",
  "{c} da yopildi": "Закрыто в {c}",
  "{c} gacha {h} soat {m} daqiqa": "До {c}: {h} ч {m} мин",
  "{c} gacha {m} daqiqa": "До {c}: {m} мин",
  "Bugun 09:00 da ochiladi · {m} daqiqa qoldi": "Откроется сегодня в 09:00 · осталось {m} мин",
  "Amortizatsiya": "Амортизация",
  "Avval ro'yxatdan o'tganmisiz?": "Уже зарегистрированы?",
  "Bilimni tekshirish · {n} savol": "Проверить знания · вопросов: {n}",
  "Boshlang'ich qiymat": "Первоначальная стоимость",
  "Botda «Start» ni bosing — shu yerda avtomatik kirasiz.": "Нажмите «Start» в боте — вход здесь выполнится автоматически.",
  "Bu hafta raqib yo'q — dushanba kuni yangi juftlar.": "На этой неделе соперника нет — новые пары в понедельник.",
  "Bu raqam avval ro'yxatdan o'tgan. Yuqoridagi «Kirish» tugmasi orqali Telegram bilan kiring yoki administratorga murojaat qiling": "Этот номер уже зарегистрирован. Войдите через Telegram кнопкой «Войти» выше или обратитесь к администратору",
  "Eskirish": "Износ",
  "Formula: QQS = jami × {r} / (100 + {r}).": "Формула: НДС = итого × {r} / (100 + {r}).",
  "Foydali muddat (yil)": "Срок полезного использования (лет)",
  "Hali yangilik yo'q. Har hafta yangi qaror va xatlar bo'yicha qisqa sharh qo'shiladi.": "Новостей пока нет. Каждую неделю здесь появляется краткий обзор новых постановлений и писем.",
  "Hisob-kitob": "Расчёты",
  "Hisoblangan ish haqi": "Начисленная зарплата",
  "Hisoblangan → qo'lga": "Начислено → на руки",
  "Hisobot va to'lov muddatlari · Telegram eslatmasi": "Сроки отчётов и платежей · напоминание в Telegram",
  "Ijtimoiy soliq (ish beruvchi to'laydi)": "Социальный налог (платит работодатель)",
  "Ijtimoiy soliq stavkasi": "Ставка социального налога",
  "Ish beruvchining jami xarajati": "Общие расходы работодателя",
  "Ish haqi, QQS, amortizatsiya": "Зарплата, НДС, амортизация",
  "JShDS (xodimdan ushlanadi)": "НДФЛ (удерживается у сотрудника)",
  "JShDS stavkasi": "Ставка НДФЛ",
  "Jamoa bali — eng yaxshi 3 kishining haftalik bali. G'olib juma 12:00 da.": "Балл команды — сумма недельных баллов трёх лучших. Победитель — в пятницу в 12:00.",
  "Jamoalar bellashuvi": "Битва команд",
  "Jamoangiz": "Ваша команда",
  "Kalkulyatorlar": "Калькуляторы",
  "Kamayib boruvchi qoldiq": "Уменьшаемый остаток",
  "Ko'nikmalar bo'yicha": "По навыкам",
  "Kun": "День",
  "Manba havolasi (lex.uz, soliq.uz)": "Ссылка на источник (lex.uz, soliq.uz)",
  "Manbani ochish": "Открыть источник",
  "Mashq": "Тренировка",
  "Mashq mavzusi": "Тема тренировки",
  "Mashq mavzusi (ixtiyoriy)": "Тема тренировки (необязательно)",
  "Mavzular bo'yicha": "По темам",
  "Muddat dam olish kuniga to'g'ri kelsa, keyingi ish kuniga o'tadi. Taqvimni superadmin yangilaydi.": "Если срок выпадает на выходной, он переносится на следующий рабочий день. Календарь обновляет суперадмин.",
  "Muddatdan 3 kun va 1 kun oldin bot sizga shaxsan eslatadi.": "За 3 дня и за 1 день до срока бот напомнит вам лично.",
  "Muddatlarni tekshirib to'ldiring: kun, oylar (bo'sh — har oy; masalan 1,4,7,10 — chorak), nomi. Bot muddatdan 3 va 1 kun oldin eslatadi.": "Заполните сроки, проверив их: день, месяцы (пусто — каждый месяц; например 1,4,7,10 — квартал), название. Бот напоминает за 3 и за 1 день.",
  "Nomi (o'zbekcha)": "Название (на узбекском)",
  "Nomi (ruscha, ixtiyoriy)": "Название (на русском, необязательно)",
  "Nomzod hisoboti": "Отчёт по кандидату",
  "O'tgan hafta: {a} — {b} · «{o}»": "Прошлая неделя: {a} — {b} · «{o}»",
  "Oylar": "Месяцы",
  "Oylar (bo'sh — har oy)": "Месяцы (пусто — каждый месяц)",
  "Oylik eskirish": "Месячный износ",
  "Provodka tuzish": "Составление проводок",
  "Provodka: Dt 9420 (yoki 2010, 9410) — Kt 0230 (masalan, mashina va uskunalar eskirishi).": "Проводка: Дт 9420 (или 2010, 9410) — Кт 0230 (например, износ машин и оборудования).",
  "Provodkalar: Dt 9420 (yoki 2010) — Kt 6710; Dt 6710 — Kt 6410 (JShDS); Dt 9420 (yoki 2010) — Kt 6410 (ijtimoiy soliq).": "Проводки: Дт 9420 (или 2010) — Кт 6710; Дт 6710 — Кт 6410 (НДФЛ); Дт 9420 (или 2010) — Кт 6410 (социальный налог).",
  "QQS": "НДС",
  "QQS bilan jami": "Итого с НДС",
  "QQS bilan → ajratish": "С НДС → выделить",
  "QQS stavkasi": "Ставка НДС",
  "QQS summasi": "Сумма НДС",
  "QQSsiz summa": "Сумма без НДС",
  "QQSsiz → QQS bilan": "Без НДС → с НДС",
  "Qisqa sharh: nima o'zgardi, kimga tegishli, qachondan": "Краткий обзор: что изменилось, кого касается, с какой даты",
  "Qo'lga → hisoblash": "На руки → начислить",
  "Qo'shimcha suhbat tavsiya etiladi": "Рекомендуется дополнительное собеседование",
  "Qoldiq": "Остаток",
  "Qonun va nazariya": "Законы и теория",
  "Qonun yangiligi": "Новость законодательства",
  "Qonun yangiliklari": "Новости законодательства",
  "Ruscha matn (ixtiyoriy)": "Текст на русском (необязательно)",
  "Sarlavha": "Заголовок",
  "Savol {n}": "Вопрос {n}",
  "Savollar har nomzodga alohida tanlanadi, javoblar serverda tekshiriladi. Hisobchi Liga": "Вопросы подбираются для каждого кандидата отдельно, ответы проверяются на сервере. Hisobchi Liga",
  "Shu mavzuda mashq qilish": "Потренироваться по этой теме",
  "Siz bu testni allaqachon topshirgansiz": "Вы уже прошли этот тест",
  "Soliq taqvimi": "Налоговый календарь",
  "Stavkalarni o'zingiz o'zgartira olasiz — qonun o'zgarsa, hisob ham to'g'ri bo'ladi.": "Ставки можно менять самостоятельно — если закон изменится, расчёт останется верным.",
  "Summa (QQS bilan)": "Сумма (с НДС)",
  "Summa (QQSsiz)": "Сумма (без НДС)",
  "Tahrirlash": "Редактирование",
  "Taqvim": "Календарь",
  "Tavsiya etiladi": "Рекомендуется",
  "Telefon raqamingizni faqat jamoa administratori ko'radi.": "Ваш номер телефона видит только администратор команды.",
  "Telegram eslatmasi": "Напоминание в Telegram",
  "Telegram orqali kiring — ballaringiz saqlanadi.": "Войдите через Telegram — ваши баллы сохранятся.",
  "To'g'ri chiziqli": "Линейный",
  "Tugatish qiymati": "Ликвидационная стоимость",
  "Vaqt tugadi. Qayta urinib ko'ring.": "Время вышло. Попробуйте ещё раз.",
  "Variant {n}": "Вариант {n}",
  "Xodim qo'liga": "Сотруднику на руки",
  "Xodim qo'liga oladigan summa": "Сумма на руки сотруднику",
  "Yangi muddat": "Новый срок",
  "Yangi qaror va xatlar · qisqa test": "Новые постановления и письма · короткий тест",
  "Yangi qonun yangiligi": "Новая новость законодательства",
  "Yangilik": "Новости",
  "Yaqin 2 oyda muddat yo'q.": "В ближайшие 2 месяца сроков нет.",
  "Yil": "Год",
  "Yillik eskirish": "Годовой износ",
  "bugun": "сегодня",
  "ertaga": "завтра",
  "guruhlarga yuborildi": "отправлено в группы",
  "har oy": "каждый месяц",
  "hisobot": "отчёт",
  "natija": "результат",
  "{n} kishi o'ynadi": "сыграли: {n}",
  "{n} kun qoldi": "осталось дней: {n}",
  "9200 tranzit: chiqib ketgan aktiv qiymati debetga yig'iladi, natija 9310 yoki 9430 ga o'tadi.": "9200 — транзитный: стоимость выбывшего актива собирается по дебету, результат переносится на 9310 или 9430.",
  "9910: kreditda foyda, debetda zarar yig'iladi.": "9910: по кредиту собирается прибыль, по дебету — убыток.",
  "Aktiv hisobvaraq debetda ko'payadi, kreditda kamayadi.": "Активный счёт увеличивается по дебету и уменьшается по кредиту.",
  "Asl savolni ham, teskarisini ham to'g'ri topgan xatolar daftardan o'chirildi.": "Ошибки, где вы верно ответили и на исходный, и на обратный вопрос, удалены из тетради.",
  "Bosqich yoki mashqda xato qilsangiz, savol shu yerga tushadi va misol bilan tushuntiriladi.": "Если ошибётесь в этапе или тренировке, вопрос попадёт сюда и будет разобран на примере.",
  "Bu provodka qaysi muomalani aks ettiradi?": "Какую операцию отражает эта проводка?",
  "Bugun": "Сегодня",
  "Bugun har savolga +{n} soniya": "Сегодня +{n} с на каждый вопрос",
  "Bugungi kuchli uchlik": "Тройка лучших сегодня",
  "Daftarda qoldi: {n} ta": "Осталось в тетради: {n}",
  "Daftarda yana {n} ta xato bor — bularni o'zlashtirgach navbat ularga keladi.": "В тетради ещё {n} ошибок — до них дойдёт очередь, когда освоите эти.",
  "Daromad kreditda tan olinadi, oy oxirida debetdan 9910 ga yopiladi.": "Доход признаётся по кредиту, в конце месяца закрывается с дебета на 9910.",
  "Debetda {c} — {n} ({k}) emas, {r} — {m} bo'lishi kerak.": "В дебете должен быть не {c} — {n} ({k}), а {r} — {m}.",
  "Farq": "Разница",
  "Final: {d}, 10:00–13:00": "Финал: {d}, 10:00–13:00",
  "G'olib bonusi": "Бонус победителя",
  "Haftalik kuchli uchlik: medal nishoni va sertifikat; oyda 2 marta kirsangiz — oylik finalga yo'llanma; 1-o'rin «Haftaning savoli»ni tuzadi.": "Тройка недели: медаль и сертификат; дважды за месяц — путёвка в месячный финал; 1-е место составляет «Вопрос недели».",
  "Har xatoni misol bilan ko'rib chiqing.": "Разберите каждую ошибку на примере.",
  "Ikkalasini to'g'ri topsangiz — xato daftardan o'chadi.": "Ответите верно на оба — ошибка удалится из тетради.",
  "Imtiyozlaringiz": "Ваши привилегии",
  "Jamoangiz uchun savol tuzing — ismingiz bilan chiqadi": "Составьте вопрос для команды — он выйдет с вашим именем",
  "Javob 10 marta farq qiladi — nol yoki vergul joyini tekshiring.": "Ответ отличается в 10 раз — проверьте нули или запятую.",
  "Javob 12 marta katta — yillik va oylik summa chalkashgan.": "Ответ в 12 раз больше — перепутаны месячная и годовая суммы.",
  "Javob 12 marta kichik — yillik summa kerak edi.": "Ответ в 12 раз меньше — нужна была годовая сумма.",
  "Javobi {n} bo'lgan masalani toping.": "Найдите задачу, ответ на которую {n}.",
  "Javobingiz 12% kam — summaga QQS qo'shilishi kerak edi.": "Ваш ответ на 12% меньше — нужно было прибавить НДС.",
  "Javobingiz 12% ko'p — QQS ajratilmagan bo'lishi mumkin.": "Ваш ответ на 12% больше — вероятно, не выделен НДС.",
  "Keyin teskari savol: provodkadan muomalani, javobdan savolni toping.": "Затем обратный вопрос: по проводке найдите операцию, по ответу — вопрос.",
  "Kontr-aktiv (eskirish, rezerv) teskari: kreditda ko'payadi, debetda kamayadi.": "Контрактивный счёт (износ, резерв) наоборот: растёт по кредиту, уменьшается по дебету.",
  "Kreditda {c} — {n} ({k}) emas, {r} — {m} bo'lishi kerak.": "В кредите должен быть не {c} — {n} ({k}), а {r} — {m}.",
  "Kunlik kuchli uchlik": "Тройка дня",
  "Kunlik kuchli uchlik mukofoti": "Награда тройке дня",
  "Majburiyat kreditda ko'payadi (qarz paydo bo'ladi), debetda kamayadi (qarz to'lanadi).": "Обязательство растёт по кредиту (возникает долг) и уменьшается по дебету (долг погашен).",
  "Mashqni boshlash": "Начать тренировку",
  "Medal nishoni ismingiz yonida; sertifikat — Profil → Sertifikatlar": "Медаль рядом с вашим именем; сертификат — Профиль → Сертификаты",
  "Misol bilan tushuntirish": "Разбор на примере",
  "Misol bilan: summa {n} so'm": "На примере: сумма {n} сум",
  "Misol bilan: summa {n} so'm bo'lsin": "На примере: пусть сумма {n} сум",
  "Natija soat {c} da e'lon qilinadi — bot g'oliblarga shaxsan xabar yuboradi.": "Итоги в {c} — бот лично напишет победителям.",
  "Nega": "Почему",
  "O'rin bugungi bosqich bali bo'yicha (teng bo'lsa — tezroq tugatgan). Mukofot {d} bosqichda: har savolga {q} soniya o'rniga ko'proq vaqt.": "Место — по баллам сегодняшнего этапа (при равенстве — кто быстрее). Награда {d} на этапе: больше времени вместо {q} с на вопрос.",
  "O'tgan hafta {p}-o'rin": "{p}-е место на прошлой неделе",
  "Oylik finalga saralangansiz": "Вы прошли в месячный финал",
  "Shu savollar boshqa savollar orasida yana chiqadi.": "Эти вопросы снова появятся среди других.",
  "Sinov rejimi": "Тестовый режим",
  "Sinov rejimi o'chirildi — to'lov talab qilinadi": "Тестовый режим выключен — требуется оплата",
  "Sinov rejimi yoqildi — hamma bepul o'ynaydi": "Тестовый режим включён — все играют бесплатно",
  "Sinov rejimini o'chirish": "Выключить тестовый режим",
  "Sinov rejimini yoqish": "Включить тестовый режим",
  "Siz": "Вы",
  "Siz 12% ni ayirdingiz — bu holatda ayirilmaydi.": "Вы вычли 12% — здесь их вычитать не нужно.",
  "Siz faqat QQS summasini hisobladingiz.": "Вы посчитали только сумму НДС.",
  "Sizda bugun har savolga +{n} soniya bor — kechagi g'alaba uchun.": "Сегодня у вас +{n} с на каждый вопрос — за вчерашнюю победу.",
  "To'g'ri javob": "Правильный ответ",
  "Tomonlar almashib qolgan: bunday yozuv teskari muomalani bildiradi.": "Стороны перепутаны: такая запись означает обратную операцию.",
  "Tuzish": "Составить",
  "Xarajat debetda tan olinadi, oy oxirida kreditdan 9910 ga yopiladi.": "Расход признаётся по дебету, в конце месяца закрывается с кредита на 9910.",
  "Xato o'chishi uchun asl savolni ham, teskarisini ham to'g'ri toping.": "Чтобы ошибка удалилась, ответьте верно и на исходный, и на обратный вопрос.",
  "Xatolar tahlili yakunlandi": "Разбор ошибок завершён",
  "Xatolar ustida ishlash": "Работа над ошибками",
  "Xatolarni tahlil qilish ({n})": "Разобрать ошибки ({n})",
  "Xususiy kapital kreditda ko'payadi, debetda kamayadi.": "Собственный капитал растёт по кредиту и уменьшается по дебету.",
  "Yechim": "Решение",
  "Yoqilganda hamma ishtirokchi to'lovsiz o'ynaydi, to'lov ekrani chiqmaydi. Sotuvni boshlaganda o'chiring.": "Когда включён, все играют без оплаты, экран оплаты не показывается. Выключите, когда начнёте продажи.",
  "chiqim yig'ildi": "собрано выбытие",
  "dushanba kuni": "в понедельник",
  "har savolga · g'olib bonusi": "на вопрос · бонус победителя",
  "ko'paydi": "увеличился",
  "kamaydi": "уменьшился",
  "qarz kamaydi": "долг уменьшился",
  "daromad tan olindi": "доход признан",
  "xarajat tan olindi": "расход признан",
  "yopildi": "закрыт",
  "zarar": "убыток",
  "foyda": "прибыль",
  "aktiv": "активный",
  "kontr-aktiv": "контрактивный",
  "majburiyat": "обязательство",
  "xususiy kapital": "собственный капитал",
  "daromad": "доход",
  "xarajat": "расход",
  "tranzit": "транзитный",
  "moliyaviy natija": "финансовый результат",
  "vaqt tugadi": "время вышло",
  "ilovadan chiqildi": "вышли из приложения",
  "s": "с",
  "mukofot bugun": "награда сегодня",
  "mukofot {d}": "награда {d}",
  "o'chiq": "выключен",
  "qarz paydo bo'ldi": "возник долг",
  "soniya har savolga": "секунд на вопрос",
  "ta o'zlashtirildi": "освоено",
  "yopildi (9910 ga)": "закрыт (на 9910)",
  "yoqilgan": "включён",
  "{n} soniya": "{n} секунд",
  "{n} ta · misol bilan": "{n} · с разбором",
  "{p}-o'rin ({d}) uchun · savolga {s} soniya": "за {p}-е место ({d}) · {s} с на вопрос",
  "«Haftaning savoli» muallifi": "Автор «Вопроса недели»",
  "«{a}» — qaysi savolning to'g'ri javobi?": "«{a}» — правильный ответ на какой вопрос?",
  "🧪 Sinov davri — bepul. Hamma bosqichlar ochiq, to'lov hozircha olinmaydi.": "🧪 Тестовый период — бесплатно. Все этапы открыты, оплата пока не взимается.",
  "Bugun hali o'ynamagan": "Сегодня ещё не играл(а)",
  "Bugun: {s}-bosqich · {r}/{n} to'g'ri · {p} ball": "Сегодня: этап {s} · верно {r}/{n} · {p} баллов",
  "Faqat bosqich ballari (kunlik mashq va blits kirmaydi). Bugun o'ynaganlar: {a}/{b}.": "Только баллы этапов (тренировки и блиц не учитываются). Сегодня играли: {a}/{b}.",
  "Havolani hamkasbingizga yuboring. U ochishi bilan o'yin boshlanadi — bu ekranni yopmang.": "Отправьте ссылку коллеге. Игра начнётся, как только он(а) её откроет — не закрывайте этот экран.",
  "Hech kim topmadi": "Никто не ответил верно",
  "Ikkalangiz bir vaqtda o'ynaysiz. Kim birinchi to'g'ri javob bersa — ochko o'shaniki va keyingi savolga o'tiladi.": "Вы играете одновременно. Кто первым ответит верно — получает очко, и оба переходят к следующему вопросу.",
  "Ikkalangiz ham shu ekranda bo'lsangiz, o'yin 3 soniyada boshlanadi.": "Когда вы оба на этом экране, игра начнётся через 3 секунды.",
  "Jamoa natijalari": "Результаты команды",
  "Jonli duel": "Живая дуэль",
  "Jonli duel yaratish": "Создать живую дуэль",
  "Jonli duel — kim tezroq": "Живая дуэль — кто быстрее",
  "Jonli duelga chaqiraman: 10 ta savol, kim birinchi to'g'ri topsa — ochko o'shaniki! ⚡": "Вызываю на живую дуэль: 10 вопросов, очко получает тот, кто первым ответит верно! ⚡",
  "Jonli duellarim": "Мои живые дуэли",
  "Kechikdingiz — raqib birinchi topdi": "Не успели — соперник ответил первым",
  "Keyingi savol {s} soniyada": "Следующий вопрос через {s} с",
  "Qoida: 10 ta savol, har biriga 1 daqiqa. Kim birinchi to'g'ri javob bersa — ochko oladi va ikkalangizga keyingi savol chiqadi. Xato javob bergan shu savolda qulflanadi.": "Правила: 10 вопросов, по 1 минуте. Кто первым ответит верно — получает очко, и обоим показывается следующий вопрос. Ответивший неверно блокируется на этом вопросе.",
  "Raqib": "Соперник",
  "Raqib ilovani ochishini kutyapmiz": "Ждём, когда соперник откроет приложение",
  "Raqib xato qildi — javob bering!": "Соперник ошибся — отвечайте!",
  "Raqibni kutyapmiz": "Ждём соперника",
  "Siz birinchi topdingiz! +1": "Вы ответили первым! +1",
  "Tayyorlaning!": "Приготовьтесь!",
  "Teng ochkoda to'g'ri javoblarga kam vaqt sarflagan yutadi.": "При равенстве очков побеждает тот, кто быстрее давал верные ответы.",
  "Xato — bu savolda qulflandingiz. Raqib javobini kuting.": "Ошибка — вы заблокированы на этом вопросе. Ждите ответа соперника.",
  "Yana jonli duel": "Ещё живая дуэль",
  "faqat sizga": "только вам",
  "o'ng tomonda — haftalik bosqich bali": "справа — баллы этапов за неделю",
  "{n} birinchi topdi": "{n} ответил(а) первым",
  "Bugungi duel": "Дуэль дня",
  "Bugungi juftlik dueli": "Парная дуэль дня",
  "Bugungi juftliklar": "Пары сегодня",
  "Duel o'ynalmadi": "Дуэль не состоялась",
  "Duel ochiq — raqibingiz bilan bir vaqtda kiring.": "Дуэль открыта — заходите одновременно с соперником.",
  "Duel soat {s} da ochiladi": "Дуэль откроется в {s}",
  "Duelga kirish": "Войти в дуэль",
  "Duelni ochish": "Открыть дуэль",
  "Durang": "Ничья",
  "Faqat provodka · 10 savol · soat {s} da ochiladi, 1 soat davom etadi": "Только проводки · 10 вопросов · открывается в {s}, длится 1 час",
  "Faqat provodka, 10 ta savol, har biriga 1 daqiqa. Kim birinchi to'g'ri javob bersa — ochko oladi va ikkalangizga keyingi savol chiqadi.": "Только проводки, 10 вопросов, по 1 минуте. Кто первым ответит верно — получает очко, и обоим показывается следующий вопрос.",
  "Ikkalangiz bir vaqtda kirmadingiz — duel hisoblanmadi.": "Вы не зашли одновременно — дуэль не засчитана.",
  "O'ynalmadi": "Не состоялась",
  "Raqib belgilangan vaqtda kirmadi — g'alaba sizga berildi.": "Соперник не зашёл вовремя — победа присуждена вам.",
  "Raqib yutdi": "Победил соперник",
  "Siz belgilangan vaqtda kirmadingiz — g'alaba raqibga berildi.": "Вы не зашли вовремя — победа присуждена сопернику.",
  "Siz yutdingiz!": "Вы победили!",
  "Soat {e} gacha kirmagan o'yinchi yutqazadi. Bot vaqt kelganda xabar beradi.": "Кто не зайдёт до {e}, проигрывает. Бот напомнит, когда придёт время.",
  "kelmagan yutqazdi": "неявка — поражение",
  "kutilmoqda": "ожидается",
  "o'ynalmadi": "не состоялась",
  "o'ynamoqda": "играют",
  "soat {s}": "в {s}",
  "yakunlandi": "завершена",
  "Bugun sizga juft chiqmadi (ishtirokchilar soni toq).": "Сегодня вам не досталось пары (нечётное число участников).",
  "Bugungi duellar jadvali": "Расписание дуэлей на сегодня",
  "Juftlar bugun soat 09:00 da tasodifiy tuziladi. Bot sizga raqibingiz va soatni yuboradi.": "Пары составляются случайно сегодня в 09:00. Бот пришлёт вам соперника и время.",
  "Juftlar dushanba soat 09:00 da tasodifiy tuziladi. Bot sizga raqibingiz va soatni yuboradi.": "Пары составляются случайно в понедельник в 09:00. Бот пришлёт вам соперника и время.",
  "Juftlar har ish kuni soat 09:00 da tasodifiy tuziladi. Keyingisi — ertaga 09:00 da.": "Пары составляются случайно каждый рабочий день в 09:00. Следующие — завтра в 09:00.",
  "Bu safar raqib kuchliroq — ertaga yana kubok": "В этот раз соперник сильнее — завтра новый кубок",
  "Chorak final": "Четвертьфинал",
  "Yarim final": "Полуфинал",
  "Final — 16:00 (yarim final g'oliblari)": "Финал — 16:00 (победители полуфиналов)",
  "Kubok g'olibi: {n}": "Победитель кубка: {n}",
  "Kubok har ish kuni soat 09:00 da tasodifiy tuziladi. Keyingisi — ertaga 09:00 da.": "Кубок составляется случайно каждый рабочий день в 09:00. Следующий — завтра в 09:00.",
  "Kubok juftlari bugun soat 09:00 da tasodifiy tuziladi. Bot sizga raqibingiz va soatni yuboradi.": "Пары кубка составляются случайно сегодня в 09:00. Бот пришлёт вам соперника и время.",
  "Kubok juftlari dushanba soat 09:00 da tasodifiy tuziladi. Bot sizga raqibingiz va soatni yuboradi.": "Пары кубка составляются случайно в понедельник в 09:00. Бот пришлёт вам соперника и время.",
  "Kunlik duel kubogi": "Кубок дуэлей дня",
  "Siz keyingi bosqichga chiqdingiz!": "Вы прошли в следующий раунд!",
  "Siz kubok g'olibisiz! 🏆": "Вы победитель кубка! 🏆",
  "Yarim final — 14:00 dan, final — 16:00 (g'oliblar o'ynaydi)": "Полуфинал — с 14:00, финал — в 16:00 (играют победители)",
};
